### ISSUE TITLE
Failed to load node 'visual_odometry_node' when running 02-realsense_camera example

### ISSUE THREAD

**Issue by KohlhardtC** [rbonghi/isaac_ros_tutorial#12]
**Steps to reproduce:**

- I followed [the directions](https://github.com/rbonghi/isaac_ros_tutorial) to launch the RealSense camera tutorial.  
- The final command as instructed is `docker run --runtime nvidia --network host --privileged rbonghi/isaac-ros-tutorial:realsense-camera`

**Expected Result:**

The following 3 nodes are expected to run:

- visual_odometry_launch_container 
- robot_state_publisher
- realsense2_camera_node

**Actual Result:**  

Only these two nodes actually run:
- robot_state_publisher
- realsense2_camera_node

The  visual_odometry_launch_container errors out with the following message:

[component_container-1] [ERROR] [1648158183.458867921] [camera.visual_odometry_launch_container]: Could not find requested resource in ament index
[ERROR] [launch_ros.actions.load_composable_nodes]: Failed to load node 'visual_odometry_node' of type 'isaac_ros::visual_odometry::VisualOdometryNode' in container '/camera/visual_odometry_launch_container': Could not find requested resource in ament index

I'm not very confident with my understanding about how ROS2 overlay / underlay environments work, but I suspect this is related to issue I'm experiencing.

**Comment by KohlhardtC** [comment]
Upon further investigation, I believe the package name changed from isaac_ros_visual_odometry to isaac_ros_visual_slam which would explain why these examples no longer work as expected

Here is a link to the new packages:
https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_visual_slam

**Comment by rbonghi** [comment]
Hi @KohlhardtC , there are updates to do on this repo with the latest packages for Isaac ROS

I will update soon

**Comment by rbonghi** [comment]
Repository updated.

Now all images work with the latest Isaac ROS and JP4.6.1
